w3c-ccg/data-integrity-test-suite-assertion

validVc.json
Removes an extraneous type from the Vc used in tests.
=> Remove second type from Vc.

CHANGELOG.md, index.js
Exports functions from this library.
This is a draft PR as we might want to clean up some of these assertions before exporting.
marked as ready as is very useful in current state.
=> Export helper funcs

CHANGELOG.md, index.js, vc-generator/generators.js, vc-generator/index.js, vc-generator/issuer.js
Features:
1. generators are more chainable now as they pass all params passed to the generator to the next generator
2. lib now exports `issueCloned` and `deriveCloned`
3. Generators have more parameters for better customization.
=> Gens pass params

assertions.js, helpers.js, index.js, package.json, suites/create.js, suites/verify.js, tests/10-issuer.js, tests/20-verifier.js, tests/mock-data.js, vc-generator/contexts.js, vc-generator/documentLoader.js, vc-generator/index.js
Features
1. adds a separate assertions.js file
2. removes klona in favor of structuredClone
3. Removes "All Rights Reserved" from multiple files.
4. Addresses: https://github.com/w3c-ccg/data-integrity-test-suite-assertion/issues/49
5. Adds a new assertion `shouldBeUrl` from [PR 53](https://github.com/w3c-ccg/data-integrity-test-suite-assertion/pull/53).
=> (A) Create assertions file

assertions.js, suites/create.js
Adds 2 tests from the latest spec text (breaks up a compound statement into 2 tests).
Also cleans up assertions a little.
=> Add proof prop test title

CHANGELOG.md, assertions.js, index.js
Addresses https://github.com/w3c-ccg/data-integrity-test-suite-assertion/issues/50
=> Add common shouldBeErrorResponse assertion.

suites/create.js, suites/verify.js, vc-generator/generators.js
Updates the test title for proof.created in the verifier
Adds a test in which created has no offset
=> Add verifier test incorrect date stamp

suites/create.js
Addresses: https://github.com/w3c-ccg/data-integrity-test-suite-assertion/issues/69
=> Add test for type DataIntegrityProof.

suites/create.js, suites/verify.js
Addresses: https://github.com/w3c-ccg/data-integrity-test-suite-assertion/issues/75
=> Update domain test

suites/create.js
=> Add context injection test.

suites/verify.js
Adds a test for:
"A conforming processor is any algorithm realized as software and/or hardware that generates and/or consumes a [conforming secured document](https://w3c.github.io/vc-data-integrity/#dfn-conforming-secured-document) according to the relevant normative statements in Section [4. Algorithms](https://w3c.github.io/vc-data-integrity/#algorithms). Conforming processors MUST produce errors when non-conforming documents are consumed."
=> Conforming processors

CHANGELOG.md, package.json, vc-generator/contexts.js
Fixes the credentials context to enable both VC 1.1 and VC 2.0 contexts.
=> CRITICAL: Fix contexts

suites/create.js
Adding normative statements of the add proof + set/chain algorithm section.
Create 3 tests, others unsure how to test at the moment. 
This needs further testing!
#73 #67 #72
=> Add proof algorithm section

suites/create.js
should be `with out` not `with`
=> Correct small typo in context injection fail reason.

assertions.js, suites/create.js, suites/verify.js
wording of this statement might be changed shortly.
=> Update proofValue test title & assertions.

vc-generator/contexts.js, vc-generator/generators.js, vc-generator/index.js
NOTE: time tests are failing because DB's implementation of DataIntegrity does not verify timestamps correctly yet.
=> Fix undefined term sd

suites/verify.js, vc-generator/generators.js, vc-generator/index.js
Adds a test for a VC where the base url is not set to null.
=> Base url null test

suites/verify.js
Please merge on approval feel free to take over.
=> Clarify prop duplicate time value tests refer to.

assertions.js
makes shouldBeErrorResponse throw reasons that can be included in the report.
=> Improve shouldBeErrorResponse w/ reasons.

suites/create.js
1. adds a period to the end of a test title
2. updates the text of a test title to match latest spec
3. breaks a compound statement into 2 tests
=> Minor corrections

suites/create.js
1. Adds two missing periods to end of test titles
2. Throws if there is no issued VC to use for a should expand to url test
3. Updates the title of the proofValue test
=> Further refine test titles

suites/algorithms.js, suites/create.js
These tests weren't run in the current test suites and I would like to see them in a separate function which can be imported independently.
=> Create seperate algorithms files and remove describe section from create suite

suites/create.js
Removed the nonce statement which isn't in the specification.
Changed the `previousProof` statement to also include arrays as indicated in the specification.
=> change previous proof statement and remove nonce test

assertions.js
some small improvements for the response assertions and
one small correction.
=> Minor improvements to common response assertions.

CHANGELOG.md, inputs/eddsa-rdfc-2022/1.1-previousProofArrayMissingFail-SimpleSigned2.json, inputs/eddsa-rdfc-2022/1.1-previousProofArrayOk-SimpleSigned2.json, inputs/eddsa-rdfc-2022/1.1-previousProofMissingFail-SimpleSigned2.json, inputs/eddsa-rdfc-2022/1.1-previousProofNotStringFail-SimpleSigned2.json, inputs/eddsa-rdfc-2022/1.1-previousProofStringMissingFail-SimpleSigned2.json, inputs/eddsa-rdfc-2022/1.1-previousProofStringOk-SimpleSigned2.json, inputs/eddsa-rdfc-2022/2.0-previousProofArrayMissingFail-SimpleSigned2.json, inputs/eddsa-rdfc-2022/2.0-previousProofArrayOk-SimpleSigned2.json, inputs/eddsa-rdfc-2022/2.0-previousProofMissingFail-SimpleSigned2.json, inputs/eddsa-rdfc-2022/2.0-previousProofNotStringFail-SimpleSigned2.json, inputs/eddsa-rdfc-2022/2.0-previousProofStringMissingFail-SimpleSigned2.json, inputs/eddsa-rdfc-2022/2.0-previousProofStringOk-SimpleSigned2.json, tests/fixtures/cryptosuites.js, vc-generator/contexts.js, vc-generator/generators.js, vc-generator/helpers.js, vc-generator/index.js, vc-generator/staticFixtures.js
MINOR release with static fixtures feature and fix for previousProof tests.
=> Correct previous proof tests

README.md
Expands the README correcting the background section and the Implementations Section
=> Revise README with improved Background and new Implementations Section
