w3c-ccg/data-integrity-test-suite-assertion

index.js, tests/mock-data.js
https://github.com/w3c-ccg/vc-api-test-suite-implementations/pull/32
Replaces `issuer.issue` with `issuer.post`
=> Use endpoint class over Issuer class.

index.js, issuedVc.js
Addresses https://github.com/w3c-ccg/data-integrity-test-suite-assertion/issues/18#issuecomment-1787883656.  The proof type was already being checked so I just updated the existing test to also check for the expected contexts.
This PR will close issues #18 and #19
=> Check if associated documents have expected contexts included.

helpers.js, index.js
- The flag `isEcdsaTests ` needs to be added since unlike the other test suites, the ecdsa test suite requires key type to be specified along with the implementation names in the report. Usage can be seen here https://github.com/w3c/vc-di-ecdsa-test-suite/pull/19
=> Add `isEcdsaTests` option to `checkDataIntegrityProofFormat()` and `checkDataIntegrityProofVerifyErrors()`

.gitignore, helpers.js, index.js
[Specs differ ](https://www.w3.org/TR/vc-di-ecdsa/#ecdsa-sd-2023) on the expected multibase encoding for `proof.proofValue`. This PR updates the assertion to use the expected assertion.
A failure will also print the expected format.
=> fix: fix expected multibase encoding format

helpers.js, index.js
We already assert that a proof.proofValue is of a specific format according to the spec (e.g., base58btc or base64url-no-ad). The only requirement on the verifier side is that the value is multibase encoded.
This updates the test title to match the language of the spec and avoids specifying any specific format.
=> Fix verifier test on invalid proof.proofValue value.

CHANGELOG.md, index.js, vc-generator/generators.js
Features:
1. exports `issueCloned`
2. Adds a new `shared` generators section for invalid cryptosuite name tests.
=> Add shared gens section & invalid cryptosuite generator

index.js, suites/create.js
1. Adds one new test from DI Spec
2. DRYs up the `this.cell` logic into a single `beforeEach` statement thanks to @JSAssassin 
3. Deprecates the `expectedCryptosuite` property which is weirdly a `boolean` when that sounds more like a string.
=> Add invalid cryptosuite test

suites/verify.js
Adds verifier test for wrong cryptosuite name
DRYs up `this.test.cell` logic into a `beforeEach` in verify suite.
=> Add wrong cryptosuite name

CHANGELOG.md, index.js, package.json, suites/create.js, tests/10-issuer.js
Adds issuer tests for cryptosuiteName and the jsonld type of cryptosuite.
This is a draft as other suites will need to turn on cryptosuite specific support via cryptosuiteName.
=> Add issuer cryptosuite type test

index.js
Patch release: passes cryptosuiteName even if `isEcdsa = true`.
=> Pass cryptosuiteName in case where isEcdsa = true.

suites/create.js
Updates the title of the issuer proof id.
p.s. there is a branch for a verifier proof id test, but it results in a jsonld safe mode evaluation so it might be better to table it for now.
=> Add assertion for issuer proof id.

assertions.js, suites/create.js
This does not add a new test, but rather uses `jsonld.expand` with a parred down version of the proof to assert on the relevant jsonld expanded form values such as if a value or term maps to a URL.
=> Should expand to url

assertions.js, suites/create.js
Adds the following test:
Cryptographic suite designers MUST use mandatory proof value properties defined in Section [2.1 Proofs](https://w3c.github.io/vc-data-integrity/#proofs), and MAY define other properties specific to their cryptographic suite.
The assertion only tests for the mandatory proof values at this time.
As time is of the essence this can be expanded to check for stricter conformance in the future.
=> Suite designers must

assertions.js, suites/create.js, suites/verify.js, tests/10-issuer.js, tests/helpers.js, tests/mock-data.js, vc-generator/contexts.js, vc-generator/generators.js
> Implementations that use JSON-LD processing, such as RDF Dataset Canonicalization [[RDF-CANON](https://w3c.github.io/vc-data-integrity/#bib-rdf-canon)], MUST throw an error, which SHOULD be DATA_LOSS_DETECTION_ERROR, when data is dropped by a JSON-LD processor, such as when an undefined term is detected in an input document.
https://w3c.github.io/vc-data-integrity/#securing-data-losslessly:~:text=Implementations%20that%20use%20JSON%2DLD%20processing%2C%20such%20as%20RDF%20Dataset%20Canonicalization%20%5BRDF%2DCANON%5D%2C%20MUST%20throw%20an%20error%2C%20which%20SHOULD%20be%20DATA_LOSS_DETECTION_ERROR%2C%20when%20data%20is%20dropped%20by%20a%20JSON%2DLD%20processor%2C%20such%20as%20when%20an%20undefined%20term%20is%20detected%20in%20an%20input%20document.
=> JSON-LD term drop

index.js, suites/verify.js
So we have a slight issue, we are regenerating the verifier test data multiple times.
This moves the verifier test data generation to `index.js` and then passes it to the verifier suite
so that the test data is only generated once per suite test run and not once per implementer.
There might be a better way of handling the before logic, but mocha has some weird rules and it will just go ahead and pass `credentials` to the test function before the before's async function has set the value of credentials so there is a small hack in this PR. I use `Object.assign` to update the properties of the object passed to the verify suite. This works and does not seem to cause any timing issues.
=> Move credentials generation to before verify tests run.

assertions.js, helpers.js, suites/create.js
1. remove checks from verificationFail
2. Add reason to verificationFail messages if provided
3. clean up createInitialVc by changing vc param to credential
4. clean up createInitialVc with some minor rearrangements
5. pass endpoint specific options to calls on vc api
=> Use credential over vc for create param & remove checks from verificationFail

suites/verify.js
This is to reflect [this pr](https://github.com/w3c/vc-data-integrity/pull/295)
=> Remove incorrectly serialized time values tests to reflect spec change

assertions.js
small nit: standardizes the way we use reason in the assertions.
=> Use reason in verificationFail over default.

CHANGELOG.md, suites/verify.js, tests/fixtures/cryptosuites.js, tests/mock-data.js, vc-generator/generators.js
Improvements
1. the MockVerifier returns 200 on success not 201 
2. moves 2 optional date stamp related tests into optionalTests.created
3. moves optionalTests to the bottom of the suite
4. Adds one missing test for `expires` to verify suite
=> May accept incorrectly serialized timestamp

tests/20-verifier.js
Corrects a small annoying issue where the test project for this library would print `keyType undefined` for some suites.
=> In test project do not show keyType undefined.

tests/10-issuer.js, tests/20-verifier.js, tests/fixtures/credentials/dl-v1.json, tests/fixtures/credentials/dl-v2.json, tests/fixtures/cryptosuites.js, tests/helpers.js
Updates the test project to work more like the actual suites where mandatoryPointers and selectivePointers are credential and VC version specific.
- also fixes a small issue where mandatoryPointers was being passed to `createVerifier` for sd/bbs verifiers.
=> Add pointers per vc version

README.md, index.js, suites/create.js, suites/verify.js
turns off optional tests by default
=> Turn off optional tests

index.js, suites/create.js, suites/verify.js, tests/fixtures/cryptosuites.js, vc-generator/generators.js, vc-generator/index.js, vc-generator/issuer.js
Adds verifier tests for proof chains and proof sets.
Closes this issue: https://github.com/w3c-ccg/data-integrity-test-suite-assertion/issues/67
=> Add proof chain tests

suites/verify.js
Adds 2 new normative statements to `suites/verify.js`
> If either securedDocument is not a map or securedDocument.proof is not a map, an error MUST be raised and SHOULD convey an error type of PARSING_ERROR.
> If one or more of proof.type, proof.verificationMethod, and proof.proofPurpose does not exist, an error MUST be raised and SHOULD convey an error type of PROOF_VERIFICATION_ERROR
Consolidates several older deprecated statements into newer statements.
=> Add proof prop statement

suites/create.js
Adds a new statement about error propagation in the create step:
> If the algorithm produces an error, the error MUST be propagated and SHOULD convey the error type.
=> Add test for error propagation.

vc-generator/generators.js
Small PATCH, removes a piece of monkey patch code that has a more elegant solution now.
Related to: https://github.com/w3c-ccg/data-integrity-test-suite-assertion/issues/56
=> Remove selectivePointers monkeyPatch from undefinedTerm generator.

assertions.js, suites/verify.js, vc-generator/generators.js
Features:
1. Renames the invalid proof type to match current spec text
2. Removes deprecated verificationMethod test as verificationMethod is now OPTIONAL
3. Removes deprecated proofPurpose tests as newer test was already using generator for it
4. small clean up in the verify suite.
=> Remove last deprecated statements

vc-generator/issuer.js
Should fix context issues we have been experiencing, the document loader class wasn't being passed properly and was getting overwritten.
=> Fix documentLoader variable name when passing to derive function
